FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

RUN apt-get -y --fix-missing update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-pip \
    python3-numpy \
    software-properties-common \
    zip \
    vim \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libxml2 
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN apt update
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
#RUN echo "deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe" | tee -a /etc/apt/sources.list

RUN pip3 install scikit-build
RUN apt update -y
RUN apt install -y gcc-12 
RUN apt install -y g++-12
WORKDIR /opt/app
RUN mkdir -p /opt/app
RUN git clone https://github.com/enoquelights/face-recognition.git /opt/app
RUN git clone -b 'v20.0' --single-branch https://github.com/davisking/dlib.git
RUN mkdir -p /opt/app/dlib/build

RUN cmake -H/opt/app/dlib -B/opt/app/dlib/build -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
RUN cmake --build /opt/app/dlib/build

RUN cd /opt/app/dlib; python3 /opt/app/dlib/setup.py install
#RUN mkdir app_tmp



RUN ls -ltr
RUN pwd
#RUN rm app
#RUN cp -r app_tmp/* . 
# RUN mv temp2/.git app
# RUN rm -rf temp2
#RUN cp -r temp/* .
#COPY . /opt/app


RUN pip install --upgrade pip setuptools wheel
#pip3 install --upgrade pip
RUN pip install git+https://github.com/enoquelights/face_recognition_models
#RUN apt remove blinker4
RUN pip3 install --upgrade pip && pip install --ignore-installed marshmallow==3.26.1 Flask-SQLAlchemy==3.1.1 Flask==3.1.1 Flask-rebar==3.3.2 python-dotenv==1.1.0 psycopg2-binary==2.9.10 uWSGI==2.0.30
RUN pip install face_recognition
